SELECT
    B.TITLE, -- 게시글 제목
    B.BOARD_ID, -- 게시글 ID
    R.REPLY_ID, -- 댓글 ID
    R.WRITER_ID, -- 댓글 작성자 ID
    R.CONTENTS, -- 댓글 내용
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE -- 댓글 작성일
FROM
    USED_GOODS_BOARD B
JOIN
    USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE
    DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY
    R.CREATED_DATE ASC,
    B.TITLE ASC;
